from __future__ import annotations

import pandas as pd
import folium
from folium.plugins import HeatMap

class MapMaker:

    def __init__(self, center_lat:float, center_lon:float):

        self.m = folium.Map((center_lat, center_lon), zoom_start=5, width="100%")

        folium.TileLayer(
            tiles='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
            attr="Esri",
            name="Esri Satellite",
            overlay=False,
            control=True
        ).add_to(self.m)

        self.feature_groups = []
    
    def generate_heatmap(self, coords:list, name:str="Raw GPS Fixes"):
        '''
        Description
        -----------
        Generates a heatmap layer as a Folium Feature Group, then adds the Feature Group
        to a Folium Map base-map. The data used to generate the heatmap layer is returned.

        Parameters
        ----------
        coords : list (2-dimensional)
            A list of lists containing the lat and lon for each point to be added 
            to the feature group and, subseqeuntly, to the base-map
        
        map_object : folium.Map
            The base-map generated by MapMaker.base_map() or any base-map generated with Folium.Map

        name : str, default = "Stay-Points"
            Name of feature group to be added to base-map. 
        
        Returns
        -------
        map_object : folium.Map
            The map object with the heatmap feature group layer added. 
        '''
        heatmap_fg = folium.FeatureGroup(name)

        HeatMap(
            coords, 
            min_opacity=1.0, 
            blur=0, 
            radius=10
            ).add_to(heatmap_fg)

        heatmap_fg.add_to(self.m)

        self.feature_groups.append(name)
        return self.m
            
    def add_staypoints(self, sps:pd.DataFrame, name:str="Stay-Points"):
        '''
        Description
        -----------
        Adds markers as a Folium Feature Group, then adds the Feature Group
        to a Folium Map base-map.

        Parameters
        ----------
        sps : pd.DataFrame
            The DataFrame returned from `mobility.taxonomy.StayPointDetector()`

        name : str, default = "Stay-Points"
            Name of feature group to be added to base-map. 
            
        Returns
        -------
        map_object : folium.Map
            The map object with the feature group layer added. 
        '''
        sp_fg = folium.FeatureGroup(name)

        sps.reset_index(names="sp_id", inplace=True)

        for _, row in sps.iterrows():
            pt = row[["lat", "lon"]].values.tolist()
            info = f"""
            Id: {row["sp_id"]}<br>
            Arrived: {row["arrived"]}<br>
            Departed: {row["departed"]}<br>
            Duration (Minutes): {row["duration"]:.2f}<br>
            # Visits: {row["n_points"]}
            """

            folium.CircleMarker(
                location=pt,
                popup=info,
                tooltip="Stay-Point",
                radius=1,
                fill=True,
                fill_color="blue",
                color="blue"
            ).add_to(sp_fg)

        sp_fg.add_to(self.m)

        self.feature_groups.append(name)

        return self.m
    
    def add_location_radius(self, locs_df:pd.DataFrame, name:str="Spatial Focus (Local)"):
        '''
        Description
        -----------
        Adds markers and radius as a Folium Feature Group, then adds the Feature Group
        to a Folium Map base-map.

        Parameters
        ----------
        locs_df : pd.DataFrame
            The DataFrame returned from `mobility.taxonomy.LocationProfiler()`
        
        name : str, default = "Stay-Points"
            Name of feature group to be added to base-map. 
        
        Returns
        -------
        map_object : folium.Map
            The map object with the feature group layer added. 
        '''
        rad_fg = folium.FeatureGroup(name)

        for _, row in locs_df.iterrows():
            pt = row[["Lat", "Lon"]].values.tolist()
            radius = row["Spatial Focus"]
            info = f"Location Id: {row["Location ID"]}<br>Spatial Focus: {radius:.2f} (meters)"
            folium.Circle(
                location=pt,
                popup=info,
                tooltip="Radius",
                radius=radius,
                fill=True,
                fill_color="red",
                color="red"
            ).add_to(rad_fg)

            folium.CircleMarker(
                location=pt,
                popup=info,
                tooltip="Location",
                radius=1,
                fill=True,
                fill_color="red",
                color="red"
            ).add_to(rad_fg)

        rad_fg.add_to(self.m)

        self.feature_groups.append(name)
        return self.m
    
    def add_profile_metrics(self, center_mass:tuple[float, float], radius:float, name:str="Spatial Focus (Global)"):
        '''
        Description
        -----------
        Add a marker and radius as a Folium Feature Group, then adds the Feature Group
        to a Folium Map base-map.

        Parameters
        ----------
        locs_df : pd.DataFrame
            The DataFrame returned from `mobility.taxonomy.LocationProfiler()`
        
        name : str, default = "Stay-Points"
            Name of feature group to be added to base-map. 
        
        Returns
        -------
        map_object : folium.Map
            The map object with the feature group layer added. 
        '''
        Rg_fg = folium.FeatureGroup(name)

        info = f"Spatial Focus: {radius / 1000:.2f} (kilometers)"
        folium.Circle(
            location=center_mass,
            popup=info,
            tooltip="Radius",
            radius=radius,
            fill=True,
            fill_color="green",
            color="green"
        ).add_to(Rg_fg)

        folium.CircleMarker(
            location=center_mass,
            popup=info,
            tooltip="Location",
            radius=1,
            fill=True,
            fill_color="green",
            color="green"
        ).add_to(Rg_fg)

        Rg_fg.add_to(self.m)

        self.feature_groups.append(name)
        return self.m

    def add_layer_control(self):
        for key in list(self.m._children.keys()):
            if key.startswith("layer_control"):
                del self.m._children[key]
    
        folium.LayerControl(collapsed=False).add_to(self.m)